---

- name: "common | config directory"
  file:
    path: "{{ directory_item }}"
    owner: root
    group: root
    mode: 0750
    state: directory
  with_items:
    - "{{ nftables_dir }}"
    - "{{ nftables_dir }}/generated.d"
  loop_control:
    loop_var: directory_item

- name: "common | config templates"
  template:
    src: "{{ config_item.src }}"
    dest: "{{ config_item.dest }}"
    backup: yes
    owner: root
    group: root
    mode: 0640
    force: "{{ config_item.force }}"
  with_items:
    - {src: nftables.conf.j2, dest: "{{ nftables_config_file }}", force: true}
    - {src: generated.nft.j2, dest: "{{ nftables_dir }}/generated.nft", force: true}
    - {src: custom.nft.j2, dest: "{{ nftables_dir }}/custom.nft", force: false}
  loop_control:
    loop_var: config_item
  notify:
    - "nftables generate rules"

- name: "common | rules files"
  template:
    src: "{{ nftables_rules_directory }}/rules/{{ rule_item }}.nft.j2"
    dest: "{{ nftables_dir }}/generated.d/{{ rule_item }}.nft"
    owner: root
    group: root
    mode: 0640
  with_items: '{{ nftables_rules }}'
  loop_control:
    loop_var: rule_item
  notify:
    - "nftables generate rules"
