---
# tasks file for securcom.nftables

- name: "Set os specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-default.yml"
  tags: always

- name: "Include packages tasks"
  ansible.builtin.include_tasks:
    file: packages-{{ ansible_os_family }}.yml
    apply:
      tags:
      - nftables
      - nftables:packages
  tags: always

- name: "Include config tasks"
  ansible.builtin.include_tasks:
    file: config.yml
    apply:
      tags:
        - nftables
        - nftables:config
  tags: always

- name: "Include service tasks"
  ansible.builtin.include_tasks:
    file: service.yml
    apply:
      tags:
        - nftables
        - nftables:service
  tags: always
