---
# tasks file for securcom.nftables

- name: "Set os specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-default.yml"
  tags: nftables

- name: "Include packages tasks"
  ansible.builtin.include_tasks: packages-{{ ansible_os_family }}.yml
  tags:
    - nftables
    - nftables:packages

- name: "Include config tasks"
  ansible.builtin.include_tasks: config.yml
  tags:
    - nftables
    - nftables:config

- name: "Include service tasks"
  ansible.builtin.include_tasks: service.yml
  tags:
    - nftables
    - nftables:service
