---
dependency:
  name: galaxy
driver:
  name: docker
lint: yamllint -c molecule/default/yaml-lint.yml .
platforms:
  - name: debian-10
    image: debian:10
  - name: centos-8
    image: centos:8
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    converge: playbook.yml
  lint: ansible-lint
scenario:
  name: github
verifier:
  name: testinfra
  lint: flake8
