---
dependency:
  name: galaxy
driver:
  name: docker
lint: yamllint -c molecule/default/yaml-lint.yml .
platforms:
  - name: debian-10
    image: debian:10
  - name: centos-8
    image: centos:8
provisioner:
  name: ansible
  lint: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint: flake8
